[workspace]
members = ["game_core", "game_tui", "renderers/wasm"]
resolver = "2"

[workspace.package]
authors = ["Karim Lalani <jimmy00784@gmail.com>"]
license = "MIT"
repository = "https://github.com/lalanikarim/terra-deck"
edition = "2021"
version = "0.1.0"

[workspace.dependencies]
bevy = { version = "0.18.1", default-features = false }
ratatui = "0.28"
crossterm = "0.28"
rand = "0.10"
wasm-bindgen = "0.2.117"
web-sys = "0.3.94"
js-sys = "0.3.94"
