[workspace]
members = ["game_core", "game_tui", "game_bevy"]
resolver = "2"

[workspace.package]
authors = ["Karim Lalani <jimmy00784@gmail.com>"]
license = "MIT"
repository = "https://github.com/lalanikarim/terra-deck"
edition = "2021"
version = "0.1.0"

[workspace.dependencies]
bevy = { version = "0.18.1", default-features = false, features = ["unapproved_paths"] }
ratatui = "0.28"
crossterm = "0.28"
rand = "0.10"
